google_client_id: "your-google-key"
google_client_secret: "your-google-key"
google_url_callback: "http://localhost:4000/auth/google/callback"
facebook_key: "your-facebook-key"
facebook_secret: "your-facebook-secret"
facebook_callback_url: "http://localhost:4000/auth/facebook/callback"
apple_key: "your-apple-key"
apple_secret: "your-apple-secret"
apple_callback_url: "http://localhost:4000/auth/apple/callback"
