// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package goqueries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type BasketItem struct {
	ID               int32
	UserID           int32
	ProductVariantID int32
	Quantity         int32
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type Category struct {
	ID          int32
	Name        string
	Description sql.NullString
}

type Conversation struct {
	ID        int32
	Name      string
	OrderID   int32
	CreatedAt sql.NullTime
}

type ConversationMessage struct {
	ID             int32
	ConversationID int32
	SenderID       int32
	Content        string
	CreatedAt      time.Time
	ReadAt         sql.NullTime
	Status         sql.NullString
}

type ConversationsUser struct {
	ID             int32
	ConversationID int32
	UserID         int32
}

type FavouriteItem struct {
	ID        int32
	UserID    int32
	ProductID int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Order struct {
	ID         int32
	UserID     int32
	Status     string
	TotalPrice int32
	ShippingID int32
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type OrderItem struct {
	ID               int32
	OrderID          int32
	ProductVariantID int32
	Quantity         int32
	CreatedAt        sql.NullTime
}

type Product struct {
	ID          int32
	Name        string
	Description string
	Price       int32
	CreatedAt   sql.NullTime
	Special     sql.NullInt32
	Option1Name string
	Option2Name string
}

type ProductCategory struct {
	ProductID  int32
	CategoryID int32
}

type ProductImage struct {
	ID        int32
	ProductID int32
	ImageUrl  string
	IsPrimary bool
	CreatedAt sql.NullTime
}

type ProductVariant struct {
	ID            int32
	ProductID     int32
	Sku           string
	Price         int32
	StockQuantity int32
	Option1Value  string
	Option2Value  string
	CreatedAt     sql.NullTime
}

type Review struct {
	ID        uuid.UUID
	SenderID  int32
	ProductID int32
	Rating    int32
	Content   string
	CreatedAt time.Time
}

type Shipping struct {
	ID          int32
	UserID      int32
	PhoneNumber string
	Address     string
	HouseNumber string
	PostalCode  string
	City        string
	Notes       string
}

type Special struct {
	ID   int32
	Name string
}

type User struct {
	ID        int32
	GoogleID  string
	Email     string
	Name      string
	AvatarUrl sql.NullString
	CreatedAt sql.NullTime
	Role      int32
}
